# -*- coding: utf-8 -*-
"""chatgpt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zi7QuX0AVuDY18PxvtuND7FsyhbrtapM
"""

# !pip install openai
# import openai

import requests
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

RAPIDAPI_KEY = "dc10ba3fa2mshb5b796ba35c4fe4p161161jsn6a0ba268f2ec"
RAPIDAPI_HOST = "chatgpt-42.p.rapidapi.com"

# Load the comprehensive database
database = {}  # Initialize an empty database

def chat_with_gpt(prompt):
    # Tokenize the user input using NLP
    tokens = word_tokenize(prompt)
    # Check if the input is a voice-based query
    if tokens[0] == "what" or tokens[0] == "how":
        # Handle voice-based queries
        pass
    else:
        # Handle text-based queries
        url = f"https://{RAPIDAPI_HOST}/conversationgpt4-2"
        headers = {
            "Content-Type": "application/json",
            "x-rapidapi-host": RAPIDAPI_HOST,
            "x-rapidapi-key": RAPIDAPI_KEY
        }
        data = {
            "messages": [{"role": "user", "content": prompt}],
            "system_prompt": "",
            "temperature": 0.9,
            "top_k": 5,
            "top_p": 0.9,
            "max_tokens": 256,     #can increase tokens for better output but limit on api upto 10000 tokens per month
            "web_access": False
        }
        response = requests.post(url, headers=headers, json=data)
        response_json = response.json()
        if 'result' in response_json:
            return response_json['result']
        else:
            return "Error: Unable to get response from ChatGPT-4"

if __name__ == "__main__":
    while True:
        user_input = input("You: ")
        if user_input.lower() == "exit":
            break
        response = chat_with_gpt(user_input)
        print("ChatGPT:", response)

