# -*- coding: utf-8 -*-
"""ChatbotUI_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L5Xrnn-psQGNFFE8CTIvjUogbyhQZ89z
"""

!pip install streamlit

import streamlit as st

def intialize_session_state():
    if "history" not in st.session_state:
        st.session_state["history"] = []

def on_click_callback():
    human_prompt = st.session_state.human_prompt
    st.session_state.history.append(human_prompt)

intialize_session_state()

st.title('Hello Student...') #title

chat_placehoder = st.container()
promptholder = st.form("chat-form")
credit_card_placeholder = st.empty()

with chat_placehoder:
    for chat in st.session_state.history:
        st.markdown(chat)

with promptholder:
  cols = st.columns((6,1))
  cols[0].text_input(
      "Chat",
      placeholder="Ask me Anything related to Rajsthan Colleges",
      label_visibility="collapsed"
  )
  cols[1].form_submit_button(
   "Send",
   type="primary",
  )

